# Generated by Django 5.2.4 on 2025-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome do Item")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("PROD", "Produto"), ("SERV", "Serviço")],
                        default="PROD",
                        max_length=4,
                        verbose_name="Tipo de Item",
                    ),
                ),
                (
                    "stock_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Quantidade em Estoque",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item (Produto/Serviço)",
                "verbose_name_plural": "Itens (Produtos/Serviços)",
                "ordering": ["name"],
            },
        ),
    ]
