# Generated by Django 5.2.4 on 2025-07-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0003_contact_logo_contact_organization_type"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("SALE", "Venda"), ("PURCHASE", "Compra")],
                        max_length=10,
                        verbose_name="Tipo de Transação",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Transação"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contacts.contact",
                        verbose_name="Contato (Cliente/Fornecedor)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantidade"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Transação",
                "verbose_name_plural": "Itens da Transação",
            },
        ),
    ]
