# Generated by Django 5.2.4 on 2025-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="additions",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Acréscimos"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Desconto"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Subtotal"
            ),
        ),
    ]
